import type { ApprovedPublicImage } from "@/lib/assets";
import type { CourseDetailKey } from "@/lib/i18n/routing";

type CourseImageKey = "adults" | "alevel" | "children" | "gcse";

const approvalDate = "2026-05-04";

function image(
  fileName: string,
  width: number,
  height: number,
  alt: string,
  source: ApprovedPublicImage["source"],
  usage: string,
): ApprovedPublicImage {
  return {
    alt,
    approvalDate,
    directory: "optimised",
    fileName,
    height,
    source,
    usage,
    width,
  };
}

export const VOLNA_IMAGES = {
  home: {
    courseCards: {
      children: image(
        "home-course-children.webp",
        1600,
        900,
        "A child studying Russian online at home with a laptop and notebook",
        "approved-stock",
        "Home children course card",
      ),
      gcse: image(
        "home-course-gcse.webp",
        1600,
        1068,
        "A teenage student preparing for exams at a desk with a laptop",
        "approved-stock",
        "Home GCSE course card",
      ),
      alevel: image(
        "home-course-alevel.webp",
        1600,
        1068,
        "An A-Level student making notes while studying online",
        "approved-stock",
        "Home A-Level course card",
      ),
      adults: image(
        "home-course-adults.webp",
        1600,
        1067,
        "An adult learner smiling while studying online with a laptop",
        "approved-stock",
        "Home adult course card",
      ),
    } satisfies Record<CourseImageKey, ApprovedPublicImage>,
    heroCollage: [
      image(
        "home-hero-event.webp",
        1600,
        1067,
        "Students and families at a Russian school event",
        "owned-school",
        "Home hero collage",
      ),
      image(
        "home-hero-classroom.webp",
        1412,
        941,
        "Children working together in a Russian classroom",
        "owned-school",
        "Home hero collage",
      ),
    ],
    welcome: image(
      "home-welcome-collage.webp",
      1600,
      913,
      "A collage of Pushkin School community and classroom moments",
      "owned-school",
      "Home welcome section",
    ),
    approach: image(
      "home-teaching-approach.webp",
      1600,
      1067,
      "A child taking an online lesson at a laptop",
      "approved-stock",
      "Home teaching approach section",
    ),
    enrollment: image(
      "home-enrolment-cta.webp",
      1600,
      1068,
      "A young learner using a laptop for an online lesson",
      "approved-stock",
      "Home enrolment CTA",
    ),
  },
  staff: {
    elena: image(
      "staff-elena-vlasenko.webp",
      300,
      300,
      "Elena Vlasenko",
      "staff-portrait",
      "Lead teaching team portrait",
    ),
    marina: image(
      "staff-marina-lucas.webp",
      235,
      300,
      "Marina Lucas",
      "staff-portrait",
      "Lead teaching team portrait",
    ),
    irina: image(
      "staff-irina-nogai.webp",
      235,
      300,
      "Irina Nogai",
      "staff-portrait",
      "Lead teaching team portrait",
    ),
    anton: image(
      "staff-anton-vlasenko.webp",
      350,
      338,
      "Anton Vlasenko",
      "staff-portrait",
      "Lead teaching team portrait",
    ),
  },
  about: {
    hero: image(
      "about-hero-school-group-large.jpg",
      4500,
      3000,
      "Children and teachers from the school community",
      "owned-school",
      "About hero",
    ),
    mission: image(
      "about-mission-online-learning.webp",
      1600,
      1067,
      "A child learning online with teacher support",
      "approved-stock",
      "About mission section",
    ),
    historyGroup: image(
      "about-history-group.webp",
      1600,
      913,
      "Pushkin School community collage",
      "owned-school",
      "About history section",
    ),
    historyVideo: image(
      "about-history-video-thumbnail.webp",
      1280,
      853,
      "A Pushkin School performance moment",
      "owned-school",
      "About history video thumbnail candidate",
    ),
    pushkinCard: image(
      "about-pushkin-card.webp",
      1600,
      411,
      "Pushkin School identity artwork",
      "owned-school",
      "About Pushkin history card",
    ),
    curriculum: [
      image(
        "about-curriculum-writing.webp",
        1600,
        1067,
        "A student writing notes while studying online",
        "approved-stock",
        "About curriculum card",
      ),
      image(
        "about-curriculum-online.webp",
        1600,
        553,
        "An online class shown on a laptop screen",
        "approved-stock",
        "About curriculum card",
      ),
    ],
  },
  courses: {
    children: {
      hero: image(
        "children-hero.webp",
        1600,
        1067,
        "A child sitting with a laptop and giving a thumbs up",
        "approved-stock",
        "Children course hero",
      ),
      overview: image(
        "children-overview-online-class.webp",
        1600,
        553,
        "An online class with a teacher on a laptop",
        "approved-stock",
        "Children course overview",
      ),
      studyOptions: [
        image(
          "children-option-bilingual.webp",
          1600,
          1067,
          "A school-age learner raising her hand during an online lesson",
          "approved-stock",
          "Children bilingual group option",
        ),
        image(
          "children-option-rfl.webp",
          1600,
          1068,
          "A child doing schoolwork at home with a laptop",
          "approved-stock",
          "Children Russian as a foreign language option",
        ),
        image(
          "children-option-private.webp",
          1600,
          1067,
          "A young learner studying online at home",
          "approved-stock",
          "Children private tuition option",
        ),
      ],
      examGuide: [],
      results: undefined,
    },
    gcse: {
      hero: image(
        "gcse-hero.webp",
        1600,
        1067,
        "A GCSE student smiling with a laptop",
        "approved-stock",
        "GCSE course hero",
      ),
      overview: image(
        "exam-hall.webp",
        1600,
        633,
        "Rows of exam desks in an examination hall",
        "approved-stock",
        "GCSE course overview",
      ),
      results: image(
        "gcse-results.webp",
        1600,
        1067,
        "Students celebrating exam results",
        "approved-stock",
        "GCSE results section",
      ),
      studyOptions: [
        image(
          "gcse-option-one-year.webp",
          1600,
          1030,
          "A student studying with a laptop at home",
          "approved-stock",
          "GCSE one-year option",
        ),
        image(
          "gcse-option-two-year.webp",
          1600,
          1067,
          "A teenage student doing homework on a laptop",
          "approved-stock",
          "GCSE two-year option",
        ),
        image(
          "gcse-option-private.webp",
          1600,
          1068,
          "A teenager preparing for exams at a desk",
          "approved-stock",
          "GCSE private tuition option",
        ),
      ],
      examGuide: [
        image(
          "mock-exam-writing.webp",
          1600,
          1068,
          "A student writing during an exam",
          "approved-stock",
          "GCSE mock exam guide",
        ),
        image(
          "exam-hall.webp",
          1600,
          633,
          "An examination hall prepared for students",
          "approved-stock",
          "GCSE exam entry guide",
        ),
      ],
    },
    alevel: {
      hero: image(
        "alevel-hero.webp",
        1600,
        928,
        "An A-Level student sitting with a laptop",
        "approved-stock",
        "A-Level course hero",
      ),
      overview: image(
        "alevel-option-two-year.webp",
        1600,
        1068,
        "A student making notes while studying online",
        "approved-stock",
        "A-Level course overview",
      ),
      results: image(
        "alevel-results.webp",
        1600,
        1067,
        "Students giving a high five after exam results",
        "approved-stock",
        "A-Level results section",
      ),
      studyOptions: [
        image(
          "alevel-option-one-year.webp",
          1600,
          1067,
          "A teenage student wearing headphones while studying at a desk",
          "approved-stock",
          "A-Level one-year option",
        ),
        image(
          "alevel-option-two-year.webp",
          1600,
          1068,
          "A student studying online and writing notes",
          "approved-stock",
          "A-Level two-year option",
        ),
        image(
          "alevel-option-private.webp",
          1600,
          1067,
          "A student wearing headphones and taking notes during an online course",
          "approved-stock",
          "A-Level private tuition option",
        ),
      ],
      examGuide: [
        image(
          "mock-exam-writing.webp",
          1600,
          1068,
          "A student writing during an exam",
          "approved-stock",
          "A-Level mock exam guide",
        ),
        image(
          "exam-hall.webp",
          1600,
          633,
          "An examination hall prepared for students",
          "approved-stock",
          "A-Level exam entry guide",
        ),
      ],
    },
    adults: {
      hero: image(
        "adults-hero.webp",
        1600,
        1067,
        "An adult learner sitting with a laptop",
        "approved-stock",
        "Adult course hero",
      ),
      overview: image(
        "adults-intermediate.webp",
        1600,
        1067,
        "An adult learner joining an online video call",
        "approved-stock",
        "Adult course overview",
      ),
      studyOptions: [
        image(
          "adults-beginner.webp",
          1600,
          1067,
          "An older learner using a laptop at home",
          "approved-stock",
          "Adult beginner option",
        ),
        image(
          "adults-intermediate.webp",
          1600,
          1067,
          "An adult learner waving during a laptop video call",
          "approved-stock",
          "Adult intermediate option",
        ),
        image(
          "adults-customised.webp",
          1600,
          1067,
          "An adult learner speaking with a teacher on a laptop video call",
          "approved-stock",
          "Adult customised option",
        ),
      ],
      examGuide: [],
      results: undefined,
    },
  } satisfies Record<CourseImageKey, {
    examGuide?: ApprovedPublicImage[];
    hero: ApprovedPublicImage;
    overview: ApprovedPublicImage;
    results?: ApprovedPublicImage;
    studyOptions: ApprovedPublicImage[];
  }>,
  courseDetails: {
    "children-primary": image(
      "children-option-bilingual.webp",
      1600,
      1067,
      "A school-age learner raising her hand during an online lesson",
      "approved-stock",
      "Children primary Russian detail page",
    ),
    "children-beginners": image(
      "children-option-rfl.webp",
      1600,
      1068,
      "A child doing schoolwork at home with a laptop",
      "approved-stock",
      "Children beginner Russian detail page",
    ),
    "children-native-speakers": image(
      "children-option-private.webp",
      1600,
      1067,
      "A young learner studying online at home",
      "approved-stock",
      "Children native speakers detail page",
    ),
    "children-online-lessons": image(
      "children-overview-online-class.webp",
      1600,
      553,
      "An online class with a teacher on a laptop",
      "approved-stock",
      "Children online lessons detail page",
    ),
    "gcse-preparation": image(
      "gcse-option-one-year.webp",
      1600,
      1030,
      "A student studying with a laptop at home",
      "approved-stock",
      "GCSE exam preparation detail page",
    ),
    "gcse-curriculum": image(
      "gcse-option-two-year.webp",
      1600,
      1067,
      "A teenage student doing homework on a laptop",
      "approved-stock",
      "GCSE curriculum detail page",
    ),
    "gcse-faq": image(
      "exam-hall.webp",
      1600,
      633,
      "Rows of exam desks in an examination hall",
      "approved-stock",
      "GCSE FAQ detail page",
    ),
    "alevel-preparation": image(
      "alevel-option-one-year.webp",
      1600,
      1067,
      "A teenage student wearing headphones while studying at a desk",
      "approved-stock",
      "A-Level exam preparation detail page",
    ),
    "alevel-curriculum": image(
      "alevel-option-two-year.webp",
      1600,
      1068,
      "A student studying online and writing notes",
      "approved-stock",
      "A-Level curriculum detail page",
    ),
    "alevel-faq": image(
      "alevel-option-private.webp",
      1600,
      1067,
      "A student wearing headphones and taking notes during an online course",
      "approved-stock",
      "A-Level FAQ detail page",
    ),
    "adult-foundations": image(
      "adults-beginner.webp",
      1600,
      1067,
      "An older learner using a laptop at home",
      "approved-stock",
      "Adult foundations detail page",
    ),
    "adult-conversation": image(
      "adults-intermediate.webp",
      1600,
      1067,
      "An adult learner waving during a laptop video call",
      "approved-stock",
      "Adult conversation detail page",
    ),
    "adult-business-russian": image(
      "adults-customised.webp",
      1600,
      1067,
      "An adult learner speaking with a teacher on a laptop video call",
      "approved-stock",
      "Adult business Russian detail page",
    ),
  } satisfies Record<CourseDetailKey, ApprovedPublicImage>,
} as const;
